# Generated by Django 4.1.1 on 2022-12-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=100, verbose_name='content name')),
                ('lname', models.CharField(max_length=100, verbose_name='lesson name')),
                ('lnumber', models.CharField(max_length=100, verbose_name='lesson number')),
                ('lfile', models.FileField(upload_to='lesson_file/', verbose_name='lesson file')),
            ],
        ),
    ]
