# Generated by Django 4.1.1 on 2022-12-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_add_paragraph_lesson_aim'),
    ]

    operations = [
        migrations.CreateModel(
            name='aims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='lesson_aim',
            name='latype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.aims', verbose_name='lesson name'),
        ),
    ]
