# Generated by Django 4.1.1 on 2023-01-04 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_aims_lesson_aim_latype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_aim',
            name='latype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.aims', verbose_name='aim type'),
        ),
        migrations.CreateModel(
            name='add_exmple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exexmple', models.TextField(verbose_name='exmple')),
                ('exanswer', models.CharField(max_length=200, verbose_name='answer')),
                ('exaim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.lesson_aim', verbose_name='lesson aim')),
                ('expnum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.add_paragraph', verbose_name='parageaph number')),
            ],
        ),
        migrations.CreateModel(
            name='add_exer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exersize', models.TextField(verbose_name='exersize')),
                ('exer1', models.CharField(max_length=200, verbose_name='answer 1')),
                ('exer2', models.CharField(max_length=200, verbose_name='answer 2')),
                ('exer3', models.CharField(max_length=200, verbose_name='answer 3')),
                ('exer4', models.CharField(max_length=200, verbose_name='answer 4')),
                ('exer_correct', models.CharField(max_length=200, verbose_name='correct answer')),
                ('exeraim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.lesson_aim', verbose_name='lesson aim')),
                ('expnum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.add_paragraph', verbose_name='parageaph number')),
            ],
        ),
    ]
