# Generated by Django 4.1.1 on 2023-01-04 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_lesson_aim_latype_add_exmple_add_exer'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_exer',
            name='exaimtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.aims', verbose_name='aim type'),
        ),
        migrations.AddField(
            model_name='add_exmple',
            name='exaimtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.aims', verbose_name='aim type'),
        ),
    ]
