# Generated by Django 4.1.1 on 2023-05-05 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_add_exer_exaimtype_add_exmple_exaimtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('ans1', models.CharField(max_length=200, verbose_name='answer 1')),
                ('ans2', models.CharField(max_length=200, verbose_name='answer 2')),
                ('ans3', models.CharField(max_length=200, verbose_name='answer 3')),
                ('ans4', models.CharField(max_length=200, verbose_name='answer 4')),
                ('correct_ans', models.CharField(max_length=200, verbose_name='correct answer')),
                ('degree', models.CharField(max_length=200, verbose_name='degree')),
                ('quiz_lesson_lname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.add_lesson', verbose_name='lesson name')),
            ],
        ),
    ]
