# Generated by Django 4.1.1 on 2023-07-09 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_add_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='download_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_file', models.FileField(upload_to='book_file/', verbose_name='book file')),
                ('lesson_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.add_lesson', verbose_name='lesson name')),
            ],
        ),
    ]
